// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCg8q462I3GrT-IUBMj6upTSc_BvJsmD-g',
    appId: '1:396401351440:web:645877d01b57ba814f2395',
    messagingSenderId: '396401351440',
    projectId: 'coach-dashboard-1',
    authDomain: 'coach-dashboard-1.firebaseapp.com',
    storageBucket: 'coach-dashboard-1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4D8cr9gf6URy08V4eAg_aLDx17Qf33No',
    appId: '1:396401351440:android:bafc9523dfe6ab214f2395',
    messagingSenderId: '396401351440',
    projectId: 'coach-dashboard-1',
    storageBucket: 'coach-dashboard-1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeATQBZ3RMLJgZUkpZQOMtfZfpmyEoUxU',
    appId: '1:396401351440:ios:1dbc8e8cfc37eaa44f2395',
    messagingSenderId: '396401351440',
    projectId: 'coach-dashboard-1',
    storageBucket: 'coach-dashboard-1.firebasestorage.app',
    iosBundleId: 'com.coachdashboard.coachDashboard',
  );
}
